### ISSUE TITLE
panic: websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by jsdevel** [fangli/rancherssh#3]
Periodically I see this error in my terminal and my connection closes:

```
panic: websocket: close 1006 (abnormal closure): unexpected EOF

goroutine 1 [running]:
main.(*WebTerm).Run(0xc4201ed8a0)
	/home/jsdevel/.gvm/pkgsets/go1.8/global/src/github.com/fangli/rancherssh/main.go:141 +0x13c
main.main()
	/home/jsdevel/.gvm/pkgsets/go1.8/global/src/github.com/fangli/rancherssh/main.go:308 +0x11d
```

This same behavior exists in the web UI shell when I have a long running process that neglects stdout.  Anytime a process logs to stdout on a frequent basis I don't have this problem.  Could there be a setting I need to set in rancher?

**Comment by jsdevel** [comment]
Possible solution [here](https://github.com/rancher/rancher/issues/2186).

**Comment by jsdevel** [comment]
The cattle machines I'm connecting to reside behind ELB which has a default idle timeout of 60 seconds.  Increasing the timeout there isn't really an option because it also means opening up the timeout for HTTP requests as well which I don't want.

Is is possible for rancherssh to "tickle" the connection to keep it open?  Perhaps send a null character every 10 seconds or so?
